### ISSUE TITLE
[Failed installation]: github.com/danimrangelb/proxy - X Binary file does not exist

### ISSUE THREAD

**Issue by denyncrawford** [installer/instl#26]
### GitHub project

https://github.com/danimrangelb/proxy

### Verbose log

> Setting up variables
 > Temporary directory: C:\Users\crawford\AppData\Local\Temp\instl-cache
 > Install location: C:\Users\crawford\instl\proxy

                          _____ _   _  _____ _______ _
                         |_   _| \ | |/ ____|__   __| |
                           | | |  \| | (___    | |  | |
                           | | | . ` |\___ \   | |  | |
                          _| |_| |\  |____) |  | |  | |____
                         |_____|_| \_|_____/   |_|  |______|

                       Instl is an installer for GitHub Projects
                                > https://instl.sh

 > Instl version: dev
 > No authentication
 i Found latest release of proxy (version: 0.0.2)
 > Getting list of assets
 i Found 3 assets in '0.0.2' - searching for one that fits your system...
 > Host architecture: amd64
 > Current architecture aliases: amd64 x86_64 x86-64 x64
 > Asset https://github.com/danimrangelb/proxy/releases/download/0.0.2/proxy-windows.zip contains windows alias windows
 > Asset https://github.com/danimrangelb/proxy/releases/download/0.0.2/proxy-windows.zip contains windows alias win
 > Asset: https://github.com/danimrangelb/proxy/releases/download/0.0.2/proxy-linux.zip, score: 0
 > Asset: https://github.com/danimrangelb/proxy/releases/download/0.0.2/proxy-windows.zip, score: 2
 > Asset: https://github.com/danimrangelb/proxy/releases/download/0.0.2/proxy-macos.zip, score: 0
 i Found asset with highest match score: proxy-windows.zip
 i Downloading asset...
 > Asset downloaded to C:\Users\crawford\AppData\Local\Temp\instl-cache\proxy-windows.zip
 i Installing proxy
 > Extracting asset...
 > Asset extracted to
 > Checking if asset was unpacked to a single directory
 > Asset was not unpacked to a single directory
 > Binary file: C:\Users\crawford\instl\proxy\C:\Users\crawford\instl\proxy\proxy-windows.exe
 > Changing PATH to include install location
 i Running clean up...
 > Removing temporary directory
 X Binary file does not exist

### Additional info

- Bug: `Binary file: C:\Users\crawford\instl\proxy\C:\Users\crawford\instl\proxy\proxy-windows.exe`
File download is correct: 
![image](https://github.com/installer/instl/assets/28849055/ebabc665-e017-4950-be82-e7403207ec65)

**Comment by MarvinJWendt** [comment]
Hi, I just tried it out, and it works fine for me.

As you already figured out, the error is here: `Binary file: C:\Users\crawford\instl\proxy\C:\Users\crawford\instl\proxy\proxy-windows.exe`. I am not sure, why your path is duplicated.

I have made some changes to the file naming. Could you please try it again and report the result? Thanks!

**Comment by denyncrawford** [comment]
Awesome, now it works!
Btw I love ths project ❤️.

**Comment by MarvinJWendt** [comment]
Glad to hear that!
