### ISSUE TITLE
Gateway error (502)

### ISSUE THREAD

**Issue by punctuations** [installer/instl#35]
When trying to install something, in my case [tablespoon](https://github.com/punctuations/tablespoon), even using `-k` to get around the SSL cert issue it returns a 502 Error, you can see this by going to [instl.sh/punctuations/tablespoon/macos](http://instl.sh/punctuations/tablespoon/macos)

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/37005919/145734560-94fd1253-5d79-41dd-8c31-0dc9c2b6d16c.png">

**Comment by MarvinJWendt** [comment]
Hi, sorry for inconvenience! The issue is fixed. I will migrate the server in the near future so that such problems won't happen again. Thanks for your patience.

**Comment by MarvinJWendt** [comment]
SSL is working too, again :)
