### ISSUE TITLE
[Bug]: instl.sh page is down

### ISSUE THREAD

**Issue by YisusChrist** [installer/instl#37]
### Description

I noticed that the demo gif displays an error when trying to retrieve the installer script:

<img width="543" alt="image" src="https://github.com/user-attachments/assets/720bacd0-83a0-4413-b2f0-79b29d918c6d">

And when I check the website I get a SSL error due to invalid/missing certificate and a 404 Not found error:

<img width="187" alt="image" src="https://github.com/user-attachments/assets/54473fb9-e991-4349-b730-96c21c9c109f">

**Comment by MarvinJWendt** [comment]
Hi, thanks for reporting! I will fix this ASAP.

**Comment by MarvinJWendt** [comment]
This should be fixed now.

**Comment by YisusChrist** [comment]
It is working again and the demo gif now displays properly. Thanks!
