### ISSUE TITLE
Unable to update cli tools

### ISSUE THREAD

**Issue by punctuations** [installer/instl#49]
As of recent, I am not exactly able to pinpoint when this happened but the instl updater stopped working entirely, it can locate the file on github and being to download it -- or what seems to be downloading -- however, it never truly updates even, even after a full reboot of the system it stays on the previous version.

**Comment by MarvinJWendt** [comment]
Hi @punctuations, which OS are you using?

If you're using linux, could you send the output of `whereis your_programm_name`?

**Comment by punctuations** [comment]
So the location of the file on mac is in `/usr/local/bin/tablespoon` and on windows it is in `C:\User\matts\instl\punctuations\tablespoon.exe`.

And removing the file then updating again does fix it for both windows and mac.

**Comment by punctuations** [comment]
Could the issue be because instl no longer requires sudo, changing the permissions required to overwrite the old file?

**Comment by MarvinJWendt** [comment]
Hmm, I am not really sure why the windows updated broke, we didn't change the logic of that, and it's working fine for my apps (installed with instl). On Linux, we previously wrote the file to `/usr/local/bin/`, but that required sudo. On new versions of instl, we write to the user home directory (`~/.local/bin/_instl/*`), and symlink the binary to `/.local/bin/`.

**Comment by punctuations** [comment]
huh,  i dont know, but just removing the file and updating seems to fix it; however, for some of the people that were beta testing my tool they also ran into the same problem as I.

**Comment by MarvinJWendt** [comment]
Did you use a terminal with admin rights before, on Windows? I could imagine that it can't override it then, without admin permissions.

**Comment by punctuations** [comment]
I don't believe so, I could be mistaken however
