### ISSUE TITLE
incorrect binary download

### ISSUE THREAD

**Issue by punctuations** [installer/instl#54]
I was trying to update, while attempting to do this the update script kept throwing an error of "bash: ./instl: cannot execute binary file", after some investigation it seems as though the binary for linux/gnu.

<img width="762" alt="image" src="https://user-images.githubusercontent.com/37005919/166968275-77a91a49-e283-4990-bad3-6e232ff17008.png">

My specs:

![output-onlineimagetools](https://user-images.githubusercontent.com/37005919/166968101-b7f11b13-cb10-406f-ac2c-402ea1fc1872.png)

The fix for this just seems to be in the individual routes for the curl command provided, as
https://instl.sh/punctuations/tablespoon/linux is the exact same as:
https://instl.sh/punctuations/tablespoon/macos

BOTH of the scripts have the following:
```
#!/bin/bash

#####################################################################
# https://instl.sh - A crossplatform installer for GitHub projects! #
#####################################################################

# Get latest version of instl
RELEASE=$(curl --silent "https://api.github.com/repos/installer/instl/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')

# Get URL to latest release of instl
URL="https://github.com/installer/instl/releases/download/$RELEASE/instl_Linux_amd64.tar.gz"

# Setup temporary directory
rm -Rf /tmp/instl-download # Remove old installation files of instl
mkdir /tmp/instl-download # Re-create temporary directory for instl

# Get latest release of instl
curl --silent $URL -L --output /tmp/instl-download/instl.tar.gz # Download instl archive
tar -zxf /tmp/instl-download/instl.tar.gz -C /tmp/instl-download # Extract instl archive

# Run instl
cd /tmp/instl-download && ./instl punctuations/tablespoon

# Remove instl and temporary files
rm -Rf /tmp/instl-download
```

whereas the macos script should not have the same URL as the linux one.

**Comment by punctuations** [comment]
also I just realized, all (including windows) is trying to download from THIS repo, not the specified one in the url

**Comment by MarvinJWendt** [comment]
Hi @punctuations, this will be fixed today! Thanks for reporting :)

**Comment by MarvinJWendt** [comment]
Fixed now, please let me know if it works! And sorry for the inconvenience, I was on vacation.
