### ISSUE TITLE
Incorrect update message

### ISSUE THREAD

**Issue by punctuations** [installer/instl#57]
With the removal of the 'sudo' from the install command the update message that shows when your version is behind should also not have sudo in it; however, it still does

**Comment by MarvinJWendt** [comment]
Thanks for reporting! I'll take a look soon :)

**Comment by MarvinJWendt** [comment]
Hi @punctuations, the update you did, should fix that for future releases, please let me know if it happens again!

![image](https://user-images.githubusercontent.com/31022056/178014662-ea6103ec-1788-41d0-994d-3863c7d516ef.png)
